version: '3'
services:
  app:
    container_name: app-server
    image: owncloud/server
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '8080'
    networks:
      - onlyoffice
    environment:
      - OWNCLOUD_TRUSTED_DOMAINS=localhost,nginx-server
    volumes:
      - ./onlyoffice/onlyoffice:/tmp/onlyoffice
      - ./onlyoffice/run.sh:/run.sh
    command: bash /run.sh
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    environment:
      - JWT_SECRET=secret
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - onlyoffice
    volumes:
      - ./onlyoffice/nginx.conf:/etc/nginx/nginx.conf
  webdav:
    image: rclone/rclone
    command:
      - serve
      - webdav
      - minio:my-bucket
      - --rc
      - --rc-addr
      - :5572
      - --rc-web-gui
      - --rc-web-gui-no-open-browser
      - --rc-no-auth
    ports:
      - 8080:8080
      - 5572:5572
    volumes:
      - ./onlyoffice/rclone:/config/rclone/
      - rclone_data:/data
    networks:
      - onlyoffice
    depends_on:
      - s3
  s3:
    image: minio/minio
    command: [ 'server', '/data', '--console-address', ':9001' ]
    environment:
      - MINIO_ROOT_USER=YOUR_ACCESS_KEY
      - MINIO_ROOT_PASSWORD=YOUR_SECRET_KEY
      - MINIO_DEFAULT_BUCKETS=my-bucket
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - rclone_data:/data
    networks:
      - onlyoffice
networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  document_data:
  document_log:
  rclone_data:
