version: '3.8'

services:
  iam:
    image: quay.io/keycloak/keycloak:23.0.3
    command: [ 'start-dev', '--http-relative-path', '/auth', '--import-realm' ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./backend/src/test/resources/realm-quickstart.json:/opt/keycloak/data/import/realm-export.json
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025