version: '3.8'

include:
  - docker-compose.graylog.yml

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  iam:
    image: quay.io/keycloak/keycloak:23.0.3
    command: [ 'start-dev', '--http-relative-path', '/auth', '--import-realm' ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./broccoli-realm.json:/opt/keycloak/data/import/broccoli-realm.json
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  monitor:
    image: prom/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  visualizer:
    image: grafana/grafana-oss
    ports:
      - 3000:3000