version: '3.8'

services:
  iam:
    image: quay.io/keycloak/keycloak:23.0.3
    entrypoint: [ "/entrypoint.sh" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./backend/src/test/resources/keycloak-entrypoint.sh:/entrypoint.sh
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025