version: '3.8'

include:
  - docker-compose.graylog.yml
  - docker-compose.onlyoffice.yml
  - docker-compose.keycloak.yml

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  monitor:
    image: prom/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  visualizer:
    image: grafana/grafana-oss
    ports:
      - 3000:3000